let suggestions = [
    "North Face",
    "Adidas",
    "Nike",
    "Tommy Hilfiger",
    "Under Armour",
    "Givenchy",
    "Versace",
    "Gucci",
    "Louis vuitton",
    "T shirt",
    "T-shirt",
    "Shorts",
    "Trousers",
    "Joggers",
    "Cargos",
    "Beanie",
    "Gloves",
];